### ISSUE TITLE
Language consistency

### ISSUE THREAD

**Issue by kelimuttu** [id-mozilla/moz-space-jkt-event-site#11]
Menus in the admin panel need more consistency. The first menu says Beranda, while we have another menu called Dashboard or Event reports. 

![Screenshot_2019-03-25 MozSpaceJKT(2)](https://user-images.githubusercontent.com/4922388/54897267-42bd3f00-4efa-11e9-8b6c-cb41dfb36da2.png)

**Comment by Dargoz** [comment]
saya ambil ini
