### ISSUE TITLE
Buat Acara - Isi Data Komunitas - fix the wording

### ISSUE THREAD

**Issue by 21lidya** [id-mozilla/moz-space-jkt-event-site#14]
1. Apakah komunitasmu pernah mengadakan acara disini ? ---> **Apakah komunitasmu pernah mengadakan acara di sini ?**

2. Masukan Komunitas Kamu* ---> **Masukan Nama Komunitas Kamu***

**Comment by kfsl** [comment]
saya mau mengerjakan isu ini
