### ISSUE TITLE
Change description to multiline text input in event registration form

### ISSUE THREAD

**Issue by dikyarga** [id-mozilla/moz-space-jkt-event-site#20]
current :  one line input text field,
expected : multi line text field 

Use Vu2-editor plugin, [installed](https://github.com/id-mozilla/moz-space-jkt-event-site/blob/master/plugins/vue2-editor.js)
Usage example : https://github.com/id-mozilla/moz-space-jkt-event-site/blob/dbf54f91b4e6fe86247b29ed21d4a495f8f8ab41/components/Events/Create/NewEventForm.vue#L13

**Comment by adzshaf** [comment]
Saya coba fix issue ini ya
