### ISSUE TITLE
Typo in dashboard page

### ISSUE THREAD

**Issue by 21lidya** [id-mozilla/moz-space-jkt-event-site#9]
1. Event belum terkonfimrasi --->Event belum terkonfirmasi
2. Selamat datang Kiholder--->Selamat datang Keyholder

<img width="1264" alt="Screen Shot 2019-03-25 at 12 24 56 PM" src="https://user-images.githubusercontent.com/44747603/54896958-0a693100-4ef9-11e9-904a-257f924c8274.png">

**Comment by Dargoz** [comment]
saya ambil ini
